version: '3.8'
services:
  php:
    build:
      context: ./docker/php
      dockerfile: dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src/LaravelStudy:/var/www/html
    depends_on:
      - db
  db:
    build:
      context: ./docker/mysql
      dockerfile: dockerfile
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3307"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=kmjak

